import React from "react"
import Layout from "../../../components/layout"
import Menu from "../../../components/aboutMenu"

export default () => (
<Layout>
<Menu />
<br />
<p>
Spanning almost thirty years, Willie Doherty’s photographic works and video installations parallel the trajectory of Derry’s recent history, albeit through a rather more oblique and critical lens than that used in conventional reportage. A retrospective of this exceptional body of work invites reflections on its role as an eyewitness testimony or aide-mémoire to a lived reality that has been obscured by political hubris and disinformation. If Doherty’s earlier work may be said to have challenged the assumptions by which social identities are constructed, the artist’s more recent work has sought to engage with the ambivalence of memory as it sustains an uneasy truce between competing socio-historical narratives. As the recurrence of sporadic acts of violence indicate, and to paraphrase James Joyce, for some, the past is consumed in the present, but the present has not yet brought forth the hoped-for future.
<br />
<br />
But there is a more subtle dimension to Doherty’s imaginative use of the camera: as a perceptual tool, disclosing the forces that shape ordinary lives and their struggle for collective and subjective agency under conditions of social, political and economic stress. In this sense, Doherty’s work becomes less of a ‘record’ of the trajectory of Derry’s socio-political history, and more a soliloquy on the efficacy of art as an interventionist and ethical practice in which what is knowable of an image, event or place, is never given but must be opened up to scrutiny. Doherty’s approach is to position us inside the play of differences that Caoimhín Mac Giolla Léith discusses as ‘dual articulation’ in his insightful essay: 3 a productive tension between image and image or image and text, between what is and is not present in the visual field, between one temporality and another, between one state of mind and another, and ultimately what these dualities disclose of the ascriptions of self and other.
<br />
<br />
To speak of Doherty’s work as an ethical practice is to point firstly to the extent to which it has confronted the photographic image itself as a less-than-transparent index of its subject, vulnerable to the abuses of deliberate or unconscious manipulation. It is worth reflecting briefly on how this practice is applied to film-based photography, and why the notion of ‘Unseen’ has such a powerful resonance throughout Doherty’s work.
<br />
<br />
By the late 1970s, photography and video had both become established as legitimate artists’ media, and this development coincided with the expansion of semiotic and cultural interrogations into the entire photographic apparatus. 4 Contrary to claims of its documentary ‘truth’, it was argued that the photograph was subject to aesthetic and ideological manipulation at every stage, from production to presentation: ‘in camera’ (limited angle of vision, selective framing and focus), during printing (cropping and masking), and in the display context by which the viewer was captured in the frame. Thus, the seen / scene was inescapably linked to what was absent from it – the ‘unseen’ outside the frame, out of focus. Hence, as a ‘record’ of what is already absent, we can draw analogies between the photograph and the eyewitness (whose vision can only ever be partial), and history as an imperfect reconstruction of the past from its traces; both of which become central preoccupations in Doherty’s work. Moreover, despite its seeming indexicality, the photograph remained surprisingly enigmatic, its horizon of meaning always in retreat from one’s desire to grasp it as an (impossible) ‘real’ – an issue so effectively captured in Doherty’s images where the horizon is absent or inaccessible to the gaze. The photograph was necessarily bound to a text – a caption or commentary – that ‘directed’ (or ‘misdirected’) its reading.
<br />
<br />
Doherty’s early use of textual overlays undermined this instrumentalisation of the photograph in several ways. The overlays in effect act as a partial screen that inhibits and hence frustrates the viewer’s desire for unmediated access to the image, which clearly has further implications in the context of what is knowable about Derry. Furthermore, although Doherty’s inscriptions may be compared to the strategy of predecessors like Hamish Fulton and Richard Long, his image-text relation rejected their romanticised view of the Irish landscape, setting in motion not only a more complex visual tension but also multiple associations: words and phrases that seem at first to be simply descriptive are found to be sourced from public statements and clichés alluding to a political ‘back story’. For instance, the photographs, Believing, Dreaming and Waiting of 1988 and False Dawn from 1990 are visually encoded to connote ‘promise’ or ‘future’, and yet the texts belie such readings. These works followed the 1985 Anglo-Irish Agreement in which hope for political resolution became compromised by a frustrating cycle of ‘talks about talks’ that broke only with the ceasefires of 1994. Similarly, three panoramic views of city lights, Looking Back, The Road Ahead and Critical Distance, all 1997, were produced during the negotiations over what in 1998 would become the Good Friday (Belfast) Agreement, when again a mixture of hope and despair prevailed. Rather more uncertain allusions are attached to the later ‘Grey Days’ series of gelatin prints, 2007. Made during the same year as the official end of the Troubles, these grey zones are infused with the eerie stillness of suspended time. Like the muted colours of Remains (Kneecapping at Gartan Square) and Remains (Kneecapping Behind Creggan Shops), both 2013, they are tonally similar to earlier black and white images of the city’s more economically deprived neighbourhoods. Seen alongside Doherty’s series of photographs originally shot in the 1980s or early 90s, but printed in 2012, the viewer may suspect that behind the political rhetoric of urban regeneration, promises of a brighter future post-Troubles have yet to materialise.
<br />
<br />
Doherty has frequently stated that his work begins with the location, thereby responding to the perceptual field before engaging with a conceptual apparatus. Doherty’s choice of location has assiduously avoided dramatising Derry: preferring to depict the interstices of the city – unpopulated streets, blank façades, dimly lit underpasses, alleys and semi-rural waysides – unremarkable and hence resistant to appropriation by the eye that looks only to capture iconic or ‘significant’ moments. Although far from arbitrary, they are zones of ‘in-distinction’. If obscured or oblique vision is the figure that most characterises his photographic images, circularity (the loop) dominates his time-based work – the one alluding to a world characterised by a lack of political vision, or will – the other to a world enmeshed historically in a cycle of repetition. Whilst Alleyway, Wasteground, Unapproved Road, all 1992, and Hoarfrost: Unapproved Border Crossing, 1991 / 2012, marked a shift away from the textual screens, the inability to see ahead remains. However, the textual overlays are soon to be replaced by spoken voiceovers as Doherty expands his practice to include tape / slide and video installations. Amongst the first of these are They’re all the Same, 1991, and The Only Good One is a Dead One, 1993, where the narrator alternates between stereotypical identities that inscribe antagonistic positions, at the same time invoking the extent to which ‘unapproved’ positions are politically silenced.
<br />
<br />
Hoarfrost gives pause for thought because this seemingly innocuous word recurs in the artist’s voiceover script to the video installation Ghost Story, 2007, a reflection on the act of remembering the trauma of Bloody Sunday in 1972: ‘The next day I walked over the waste ground that was now marked by deep tyre tracks and footprints, fixed in low relief and highlighted by a sharp hoar frost.’ 6 Doherty’s repeated reference to ‘hoarfrost’ resonates as the authentic voice of the eyewitness registering the sometimes incidental but perceptual details of a scene. Indeed, it is the unpredictability of how and what an eyewitness remembers of an event (and how this may be silenced by ‘official accounts’) that is the subject of the tape / slide installation 30th January 1972, 1993.
<br />
<br />
Increasingly, it is the incidental perceptual detail that dominates Doherty’s later work, beginning with a number of photographs from 1993 thematically entitled ‘Incident’. Tyre treads etched in the road, plastic detritus and bits of discarded clothing, abandoned cars or interiors, close-ups of shell casings or circuit boards nestled in undergrowth, stains that resemble spilt blood. Ordinarily such details may seem inconsequential, but in Northern Ireland they become charged with a terrible significance. In Doherty’s work they offer the viewer a narrative potential: traces of an event, drawing on codes that we recognise from forensic crime television series, and whose status the artist interrogates further in time-based formats as ‘evidential truth’ of the past. But in this approach, too, we are confronted with uncertainty – a blurring of the boundaries between the signs of true crime and fiction that is highlighted in the set of diptychs entitled Small Acts of Deception, 1997 – where the distinction between ‘real’ and ‘staged’, or even between ‘informant’ and ‘witness’, is indeterminable.
<br />
<br />
That the truth of subjective testimony cannot be guaranteed, accounts for the increased dependence by inquiries on the supporting evidence of ‘objective’ material ‘clues’. But if eyewitness testimony can bear false witness, a charge successfully proven against the organs of the state by the Saville inquiry, 7 forensics can be misled by the time-honoured practice of planted ‘evidence’. Perhaps, however, feelings and sensations take priority in traumatic memory, such that, as the text of Ghost Story speculates, the past is experienced as exuding from the location itself – daytime ‘wraiths’ that enjoin Joyce’s nightmare of history. In any case, ‘hoarfrost’ recalls Michel de Certeau’s assertion that (involuntary) memory always comes ‘from the outside’, as something forgotten but recalled by a word, an image, a smell, a sound: ‘Memory is played by circumstances, just as a piano is played by a musician and music emerges from it when its keys are touched by the hands. Memory is a sense of the other.’
</p>
<br />
<br />
<h3><i>‘"History", Stephen said, "is a nightmare from which I am trying to awake."’</i></h3> <h4 style={{textAlign: "right"}}>James Joyce</h4>
<p>
My initial visit to Derry was in late 1989, to witness ‘at first hand’ the context of Willie Doherty’s early photographs, in order to write the catalogue essay for Unknown Depths. 10 At that time, the territory was in its second decade of military occupation; and Doherty’s work, infused with allusions to boundaries (as hallucinatory as they were concrete), political hubris, surveillance and suspicion, reflected the city as ‘unhomely’. My recent return visit was to a city that had been ‘de-militarised’ and given a cosmetic makeover, although territorial markers – flags, murals and boundary walls – remained in evidence.
<br />
<br />
Most striking was that Derry had become a city of memorials, but these were of two kinds: the prominently displayed public monument and the simple neighbourhood plaque or shrine. What characterises the former is their surprisingly conventional formality: the Republican memorial in the Creggan, and the Hunger Strike and Bloody Sunday memorials in Rossville Street, are all variations of the ‘obelisk’, the traditional state-sanctioned form of the inscribed war memorial (and the Free Derry Wall, now a free-standing gable end, itself risks morphing into an obelisk). These are more than understandable if, as Michael Rowlands suggests, ‘triumphalism, the reason why most memorials are monuments, achieves [a way out of melancholia] through the assertion of collective omnipotence and by banishing from memory those acts of humiliation when the nation failed to protect its young.’ 11 But if the intention is to ‘forget the pain’, it is precisely this impossibility that is reflected both in the little plaques and shrines that mark the crisis of personal loss and the preoccupations of Doherty’s work. As Doherty has himself written: ‘The problem with forgetting / the problem with remembering’. 12
<br />
<br />
For this reason, the violence of the past cannot be erased by a willed act of reconciliation, but at best, as the conclusion of the Peace Process in 2007 indicated, by an act of amnesty: 13 a social contract by which conflicting constituencies agree to deliberately ‘forget’ their differences in the public domain – or better, as Kearney says, to forego the ‘debt accrued by memory of crimes’. 14 Amnesty, however, is not amnesia.
<br />
<br />
In speaking of what he calls the ‘pathological-therapeutic’ level of memory, rooted in ‘wounds and scars’, Ricoeur notes that there are places where there is an excess of memory and others where there is an excess of forgetting, urging a balance between a duty to forget and a duty to remember, so that the egregious acts of the past are not repeated. 15 According to Freud’s writing on trauma, such excesses are on the side of repetition and melancholia, which prevent reconciliation with the lost ‘object’ of the past, be it person or ideal. Classing this failure as an ‘abuse’ of memory, Ricoeur notes that ‘the diseases of memory are basically diseases of identity’, a displacement of selfhood to its external affiliations (from ‘who’ to ‘what’). 16 Narratives may abuse memory through various manipulations – and amongst these he cites certain ‘heroic’ commemorations (including their rituals, festivals, myths), which ‘attempt to fix the memories in a kind of reverential relationship to the past’. The monument is a civic obligation to the community to memorialise its collective memory, but Adrian Forty suggests that such objects are the ‘enemy of memory, they are what tie it down and lead to forgetfulness’, insofar as ‘they permit only certain things to be remembered, and by exclusion cause others to be forgotten’. 17 If, in the monument, the past is abstracted, idealised and institutionalised, what is ‘forgotten’ is the pain, loss and resentment that accompany violent conflict, a poignant reminder of which returns in the simple plaques and shrines, which may be protection against the loss of memory – or perhaps against the loss of reasons for sustaining resentment…
<br />
<br />
One such shrine now exists on the Letterkenny Road, which Doherty presents as To the Border: A Fork in the Road, 1986 / 2012. Among a group of photographs titled ‘Lapse’, from his archive but newly printed, it presents an unusual temporal displacement. The image marks the site of an event that had still to happen at the time the photograph was taken; and in an uncharacteristic elaboration of the title, Doherty notes gruesome details of this death. Two related works assign historical significance after the event: Face Down: Alleyway Used for Cover on January 30th, 1972, 1992 / 2012; and Silence: After a Kneecapping, 1985 / 2012. All tell of stories and places unremarked by the grand narratives memorialised in monuments.
<br />
<br />
Ricoeur notes another form of narrative directed towards justice and the future that he calls ‘telling otherwise’, in which not only the victors but also the victims of history get to tell their stories. 18 This resonates in the works cited above and is consistent with Doherty’s refusal to reduce complexity to an exclusive duality, or ‘divide’, that renders ‘unseen’ other perspectives. 19 Indeed, the artist’s various allusions to the blurring of topographic boundaries may be taken as metaphors for the unstable criteria by which the ‘self’ seeks to distinguish itself from the ‘other’.
<br />
<br />
Hence, if Doherty’s work is a ‘telling otherwise’, it is in its disclosure of what is shared by, not what separates ‘self’ and ‘other’. In this respect Doherty’s images of urban neglect render indistinguishable the housing estates on both sides of the ‘divide’. Contemplating these, the outsider wonders why the working class poor didn’t unite across sectarian lines against the political élite – but then one recalls Antonio Gramsci’s commentary on how the socially disenfranchised are coerced into identifying with the values of the middle classes against their own political interests, 20 exacerbated by the divisive legacy left by British imperialism wherever in the world its tentacles have reached.
<br />
<br />
The bathos of this history is condensed in several works that contemplate the relationship of the Loyalist / Protestant Fountain Estate to the city, which Doherty identifies as an inner city ‘enclave’ (Enclave: Dividing Wall, 1987 / 2012). 21 The Siege of Derry took place in 1689, and yet a siege mentality is still tenaciously held and materialised in the ‘gated’ Bishop’s Gate entrance to the Fountain, and in the defensive walls and fences that Doherty captures in several other works, including Last Bastion, 1992, and Shadow of the Walls, 1993, (and, of course, in the Apprentice Boys commemorative parade). I first took God Has Not Failed Us, 1990, and At the Verge, 1992, to be reproaches about such sectarian intransigence, but on reflection they seem far more nuanced. God Has Not Failed Us shows the narrow lane between the palisaded city walls and the dilapidated Fountain, but it leads the eye only to the surviving tower of the old Derry Gaol flying the Union Jack. Thus the local residents seem imprisoned by an allegiance that (in an ironic inversion of Doherty’s title) failed them and by a past that could have taken a different path to the future. 22 At the Verge, shows the now demolished Fountain flats in the background, whose residual lives Doherty captured in, amongst other works, Abandoned Interiors, 1997; but, inscribed with the word ‘mute’, the work prompts thoughts of how the marginalised of society of whatever allegiance become silenced by the rhetoric of the powerful.
<br />
<br />
The nightmare of history is a leitmotif weaving through the first (‘Telemachian’) episodes of Joyce’s novel, Ulysses, and it is couched as a quest for self realisation in the face of filial dispossession by what Gilles Deleuze in another literary context called ‘monstrous devouring fathers’: ‘if humanity can be saved, and the originals reconciled, it will only be through the dissolution or decomposition of the paternal function’, whereby the ‘sons’ can find their own space of agency, through not predetermined concepts, but percepts of living conditions. 23 For Stephen Dedalus this paralysis of the future is attributable to ‘the imperial British state and the holy Roman catholic and apostolic church’. More than a hundred years later, we catch echoes of Joyce’s exasperation with a past that obscures a productive vision of the future in the artistic practice of Willie Doherty: despite modest concessions, the baleful effects of these ‘fathers’ still resonate in the affiliations of their heirs in Joyce’s ‘black north and true blue bible’ – heirs who remain bereft of origins that they can fashion into a commonality beyond the filial constraints of religion, nationalism and ideology.
<br />
<br />
Joyce and Doherty’s work share the search for an exit from the more crippling effects of history as it resonates in the memories of the living. Among the structural devices common to writer and artist is a critique of the medium of transmission, in itself an act of resistance against the manipulative use of words and images by vested interests. Both deploy multiple perspectives in acknowledgement that no single viewpoint can guarantee the ‘truth’ of the past. Moreover, Doherty’s work is as intimately associated with Derry and what it has come to signify as Joyce’s work is inseparable from Dublin; but if this is where their work begins it is by no means where it ends. As Joyce said, ‘For myself I always write about Dublin because if I can get to the heart of Dublin I can get to the heart of all the cities in the world. In the particular is contained the universal’. 24 If a city can represent a ‘universal’, it is in the way place and lives are mutually articulated, where repetition may be a source of comfort or constraint, and memory a palliative or poison. Joyce described art as the production of ‘epiphanies’, and it is in its provocation of such insights that Doherty’s work may be seen as an ethics of memory and action that seeks a balance between a duty to forget and duty to remember, and a ‘space of agency through not predetermined concepts but percepts of living conditions’, 25 the ground from which a truly collective future may be wrought.</p>
</Layout>
)
